# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\";\n\x0bMessageData\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x02\"\x19\n\nReturnData\x12\x0b\n\x03ret\x18\x01 \x01(\r2G\n\x08Listener\x12;\n\x0cListenStream\x12\x13.server.MessageData\x1a\x12.server.ReturnData\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEDATA._serialized_start=24
  _MESSAGEDATA._serialized_end=83
  _RETURNDATA._serialized_start=85
  _RETURNDATA._serialized_end=110
  _LISTENER._serialized_start=112
  _LISTENER._serialized_end=183
# @@protoc_insertion_point(module_scope)
